[FEATURE] Recent update warning
th0r/npm-upgrade pull request #81
Opened 2022-06-28 08:37 UTC by IchiiDev

This feature was suggested by Issue #80, I have implemented it on my fork.
What has been asked is basically to add a warning if a package was pushed recently, to prevent package hijacking and malwares.

What I have done to implement it:
1. Everytime a dependency is prompted, it will fetch https://registry.npmjs.com/:package to fetch the version's publication date
2. Will check if 3 days have passed since the last publish
3. If not then it will throw an error, a warning or an info telling the user the package was pushes recently and that they should be careful when upgrading.

This has been tested with some recently pushed packages and it works as expected. I will be available during the next few days to edit if any review requires changes.

![](https://i.discord.fr/JiY3.png)

2022-12-31 04:29 UTC, houd1ni commented
hi, @IchiiDev  !
PRs here are quite stuck, hence maybe make an independent project began from the fork ? Seems that this one could be a nice start.
I have a huge issue when being at bad network environments and almost cannot `npm-upgrade` at all, therefore  willin' to commit some code into there asap.

2022-12-31 05:14 UTC, IchiiDev commented
I'm going to send an email directly to @th0r to suggest giving ownership/management to someone else, both on the NPM registery and GitHub. If no answers ensues I will try and send a ticket to NPM's support to request ownership due to inactivity. 😄

2022-12-31 05:28 UTC, houd1ni commented
> I'm going to send an email directly to @th0r to suggest giving ownership/management to someone else, both on the NPM registery and GitHub. If no answers ensues I will try and send a ticket to NPM's support to request ownership due to inactivity. 😄

Nice! Tag me here, please, with any news!

2023-01-14 05:55 UTC, houd1ni commented
@IchiiDev salut! Any news ?

2025-05-14 14:49 UTC, ImLunaHey commented
@IchiiDev any chance you'd be able to reopen this and check it works with the latest version?

2025-05-14 14:56 UTC, IchiiDev commented
I could check, I just saw that @th0r reacted in the referenced Issue, so I'll open it again if they are willing to take a look at the changes if up to date. I closed the PR due to previous inactivity.

2025-05-15 12:28 UTC, IchiiDev commented
![image](https://github.com/user-attachments/assets/419eaea7-e07a-4eff-8ff4-aaf517038f32)
Still works as intended 3 years ago :smile: 

Aside from some ESLint errors I just fixed, nothing to report here. Waiting for review. (see #80)

2025-05-15 13:07 UTC, ImLunaHey commented on src/commands/check.js
> +    publishedDate = new Date(publishedDate);
nit: `(await getVersionPublicationDate(name, to)) ?? new Date(publishedDate);` would be nicer than using a `let`

2025-05-15 14:21 UTC, th0r requested changes

2025-05-15 14:21 UTC, th0r commented on src/commands/check.js
> +        '^',
Why do we only take `^` into account? What about `~` and other possible ways to specify semver versions?

2025-05-15 14:21 UTC, th0r commented on src/commands/check.js
> +    const recommendedDatePrior = new Date(Date.now() - (1000 * 60 * 60 * 24 * 3));
It would be nice to allow to configure these time periods and not hardcode them.

2025-05-15 15:10 UTC, IchiiDev commented
Will check this tomorrow

2025-05-19 13:35 UTC, IchiiDev commented on src/commands/check.js
> +    const recommendedDatePrior = new Date(Date.now() - (1000 * 60 * 60 * 24 * 3));
Would that be done through preset values, command flags or a config file ?

2025-06-02 14:02 UTC, th0r requested changes

2025-06-02 14:02 UTC, th0r commented on src/commands/check.js
> +    }
Why do we need to do this for each updated module and not only once somewhere above the loop?

2025-06-02 14:02 UTC, th0r commented on src/commands/check.js
> +        /[~^]/,
As I mentioned in the previous comment, there are other ways to specify versions in semver besides `~` and `^` e.g. `>=` and I'm not sure how we can properly handle it here. Maybe `semver` package has some method that allow to remove all these special characters from the version number?

2025-06-02 14:02 UTC, th0r commented on src/stringUtils.js
> +  const match = string.match(/(\d+)([smhd])/);
```suggestion
  const match = string.match(/^(\d+)([smhd])$/);
```

2025-06-02 14:02 UTC, th0r commented on src/packageUtils.js
> +export const getVersionPublicationDate = _.memoize(async (moduleName, version) => {
By default `memoize` will take the first argument as a cache key which means the `version` argument will be ignored.

2025-06-02 14:02 UTC, th0r commented on src/commands/check.js
> +    const publishedDate = new Date(await getVersionPublicationDate(name, to));
Can we get this info for all the outdated modules before the loop as currently it leads to a small delay after each answer. We can even do that in the background while user answers the questions for the previous modules.

2025-06-02 14:02 UTC, th0r commented on src/commands/check.js
> +    // This is 3 days prior to execution time.
It's now configurable so we need to change the comment

2025-06-02 14:02 UTC, th0r commented on src/commands/check.js
> +    let cautionTime = toTimespan(config.recentUpdates?.caution ?? '1d');
1. Let's extract default values into some constant please
2. Let's add a section in `README.md` about these config values please

2025-06-02 14:53 UTC, IchiiDev commented on src/commands/check.js
> +        /[~^]/,
This is tricky because the only way to properly handle it is to load all published version somewhere and compare the range to what's been fetched. What I don't understand is why the new version semver is a range and not just a version tag.

2025-06-02 15:04 UTC, IchiiDev commented on src/commands/check.js
> +        /[~^]/,
I have made a fix, let me know what you think

2025-06-03 08:15 UTC, th0r commented on src/commands/check.js
> +        /[~^]/,
> What I don't understand is why the new version semver is a range and not just a version tag.

Because the special characters in the version numbers in `package.json` must be preserved during a version bump e.g. `^1.0` after an upgrade must keep the `^` suffix.

2025-06-03 16:01 UTC, th0r requested changes

2025-06-03 16:01 UTC, th0r commented on src/commands/check.js
> +    await Promise.all(modulesToUpdate.map(async ({name, to}) => {
This will wait for published dates for **all modules** to be fetched before going further so it won't be done in the background

2025-06-03 16:01 UTC, th0r commented on src/commands/check.js
> +  if (!handler.publishedDatesCache) {
Why do you need to store it as a property in the `handler`?

2025-06-03 16:01 UTC, th0r commented on src/commands/check.js
> +  }
Sorry, but I don't get what this code does. You have already fetched all the published dates above.

2025-06-05 09:20 UTC, ImLunaHey commented on src/commands/check.js
> +  });
what're you actually trying to do because this just doesn't look right?

2025-06-05 11:09 UTC, IchiiDev commented on src/commands/check.js
> +  });
I am adding every promises to the object so that they can resolve in the background and be awaited once needed in the loop.

2025-06-05 14:09 UTC, ImLunaHey commented on src/commands/check.js
> +  });
that's not really how promises work. nothing will resolve until they're awaited.

2025-06-05 15:08 UTC, IchiiDev commented on src/commands/check.js
> +  });
> that's not really how promises work. nothing will resolve until they're awaited.

What would be the best way to approach this issue then?

2025-06-05 16:29 UTC, ImLunaHey commented on src/commands/check.js
> +  });
what're you actually trying to do?

2025-07-25 04:41 UTC, drillskibo commented on src/commands/check.js
> +  });
@IchiiDev *awaiting* answer here 😁

2025-07-25 05:03 UTC, IchiiDev commented on src/commands/check.js
> +  });
Well, I was actually waiting for someone to give some pointers on the issue, but work on the side didn't leave me much time to fix this PR.

Maybe if someone could give me any actual clue instead of asking me what I want to do? After two years I kind of gave up on the actual thing and kept the PR open out of courtesy to not throw everything in the trash. 

So would anyone have any clue on how to implement the background resolution of promises the proper way?

2025-07-25 10:53 UTC, ImLunaHey commented on src/commands/check.js
> +  });
the reason im asking is because i dont see why you need to do any of this background stuff. just resolve it as is.

2025-07-25 11:02 UTC, IchiiDev commented on src/commands/check.js
> +  });
@th0r asked for it, to reduce latency after each prompt.

2026-08-11 12:46 UTC, closed without merging